import { init, defaultDevice, numpy as np, type Device } from '@jax-js/jax'
import type { Counters } from './engine.js'

type BackendMode = 'webgpu' | 'wasm'
type Tensor = { dtype: number; shape: number[]; group: number; bits: number; data: Uint8Array }

function hf (x: number) { const s=x>>>15,e=(x>>>10)&31,f=x&1023; if(!e)return((s?-1:1)*Math.pow(2,-14)*f)/1024; return(s?-1:1)*Math.pow(2,e-15)*(1+f/1024) }
function hfIeee (x: number) { const s=x>>>15,e=(x>>>10)&31,f=x&1023; if(!e)return((s?-1:1)*Math.pow(2,-14)*f)/1024; if(e===31)return f?NaN:(s?-1:1)*Infinity; return(s?-1:1)*Math.pow(2,e-15)*(1+f/1024) }
function fwht (a: Float32Array) { for(let n=1;n<a.length;n<<=1)for(let i=0;i<a.length;i+=n<<1)for(let j=0;j<n;j++){const x=a[i+j],y=a[i+j+n];a[i+j]=x+y;a[i+j+n]=x-y} const q=1/Math.sqrt(a.length);for(let i=0;i<a.length;i++)a[i]*=q }
function unpack (t: Tensor,row:number,inPad:number,rowBytes:number){const b=t.bits,out=new Uint8Array(inPad);if(b===5){const off=row*rowBytes;for(let i=0;i<inPad;i++){const c=(t.data[off+(i>>2)]>>((i&3)*2))&3;out[i]=c===3?0:c+1}return out}const off=row*rowBytes,mask=(1<<b)-1;for(let i=0;i<inPad;i++){const bit=i*b,bi=off+(bit>>3),sh=bit&7;let v=t.data[bi]>>sh;if(sh+b>8)v|=t.data[bi+1]<<(8-sh);out[i]=v&mask}return out}
function decodeCq(t:Tensor,cb:Float32Array){const out=t.shape[0],dim=t.shape[1],g=t.group||128,b=t.bits,inPad=Math.ceil(dim/g)*g,rb=b===5?inPad/4:(inPad*b)/8,groups=inPad/g,rowBytes=rb+groups*2,dst=new Float32Array(out*dim),code=b===2?cb.subarray(0,4):b===3?cb.subarray(4,12):b===4?cb.subarray(12,28):new Float32Array([-1.2240064,0,1.2240064].map(v=>v/Math.sqrt(g))),dv=new DataView(t.data.buffer,t.data.byteOffset,t.data.byteLength),tmp=new Float32Array(g);for(let r=0;r<out;r++){const ids=unpack(t,r,inPad,rowBytes),rowOffset=r*rowBytes;for(let q=0;q<groups;q++){const scale=hf(dv.getUint16(rowOffset+rb+q*2,true));if(!Number.isFinite(scale)){tmp.fill(0);continue}for(let j=0;j<g;j++)tmp[j]=(code[ids[q*g+j]]||0)*scale;fwht(tmp);for(let j=0;j<g&&q*g+j<dim;j++)dst[r*dim+q*g+j]=tmp[j]}}return dst}
function decodeWeights(m:any){return m.t.filter((t:Tensor)=>t.dtype!==4).map((t:Tensor)=>{if(t.dtype===1){const d=new DataView(t.data.buffer,t.data.byteOffset,t.data.byteLength),a=new Float32Array(t.data.byteLength/2);for(let i=0;i<a.length;i++)a[i]=hfIeee(d.getUint16(i*2,true));return a}if(t.dtype===2)return new Float32Array(t.data.buffer,t.data.byteOffset,t.data.byteLength/4).slice();return decodeCq(t,m.cb)})}

export class JaxRuntime {
  m:any; w:Float32Array[]; counter:Counters|null=null; weightBytes=0; peakBytes=0; mode:BackendMode
  private constructor(m:any,weights:Float32Array[],mode:BackendMode){this.m=m;this.w=weights;this.mode=mode;this.weightBytes=weights.reduce((n,x)=>n+x.byteLength,0);this.peakBytes=this.weightBytes}
  private static async selectDevice(preferred:BackendMode){let mode=preferred;const wanted:Device=preferred==='webgpu'?'webgpu':'wasm';const available=await init(wanted);if(!available.includes(wanted)){if(preferred!=='webgpu')throw Error('jax-js WASM backend 不可用');const fallback=await init('wasm');if(!fallback.includes('wasm'))throw Error('jax-js 没有可用 backend');mode='wasm'}defaultDevice(mode);return mode}
  static async create(m:any,preferred:BackendMode='webgpu'){let mode:BackendMode;try{mode=await this.selectDevice(preferred)}catch(error){throw Error(`jax-js 初始化失败: ${(error as Error)?.message||error}`)}return new JaxRuntime(m,decodeWeights(m),mode)}
  static async createFromWeights(m:any,weights:Float32Array[],preferred:BackendMode='webgpu'){let mode:BackendMode;try{mode=await this.selectDevice(preferred)}catch(error){throw Error(`jax-js 初始化失败: ${(error as Error)?.message||error}`)}return new JaxRuntime(m,weights,mode)}
  async mm(a:Float32Array,m:number,k:number,wi:number,n:number){this.counter&&(this.counter.dispatches++,(this.counter.flops+=2*m*k*n));const weight=this.w[wi];if(!weight)throw Error(`GEMM weight ${wi} 不存在`);const need=n*k;if(weight.length<need)throw Error(`GEMM weight ${wi} 太小：需要 ${n}x${k}=${need}，实际 ${weight.length}`);const aa=np.array(a).reshape([m,k]);const bb=np.array(weight.subarray(0,need)).reshape([n,k]);const yy=np.einsum('mk,nk->mn',aa,bb);const data=await yy.data();const out=new Float32Array(data);this.peakBytes=Math.max(this.peakBytes,this.weightBytes+a.byteLength+out.byteLength);const bad=out.findIndex(x=>!Number.isFinite(x));if(bad>=0)throw Error(`jax-js GEMM 输出在索引 ${bad} 出现 NaN/Infinity`);return out}
}
