type Tensor={dtype:number; shape:number[]; offset:number; nbytes:number; group:number; bits:number; data:Uint8Array};
type Cact={geometry:Record<string,number>; tensors:Tensor[]; codebook:Float32Array; tokenizer?:RefTokenizer};
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const TAG=0x05e12a83, HEADER=120, REC=48;
const gpuStatus=$<HTMLDivElement>('gpuStatus'), messages=$<HTMLDivElement>('messages'), progress=$<HTMLDivElement>('progress');
type GPUDevice = any;
const GPUBufferUsage:any={STORAGE:1,COPY_DST:8,COPY_SRC:4}; const GPUShaderStage:any={COMPUTE:4};
let device:GPUDevice|null=null, model:Cact|null=null;

class RefTokenizer {
  pieces:string[]=[]; scores:number[]=[]; types:number[]=[]; p2id=new Map<string,number>(); byteId=new Map<number,number>();
  constructor(blob:Uint8Array){const dv=new DataView(blob.buffer,blob.byteOffset,blob.byteLength);let o=24;const n=dv.getUint32(0,true);for(let i=0;i<n;i++){const score=dv.getFloat32(o,true);const type=dv.getUint8(o+4);const len=dv.getUint16(o+5,true);o+=8;const p=new TextDecoder().decode(blob.slice(o,o+len));o+=len;this.pieces.push(p);this.scores.push(score);this.types.push(type);this.p2id.set(p,i);if(type===4)this.byteId.set(parseInt(p.slice(3,5),16),i)}}
  encode(text:string){const s='▁'+text.replaceAll(' ','▁');const ids:number[]=[];for(const ch of s){const id=this.p2id.get(ch);ids.push(id??3)}return ids}
  decode(ids:number[]){return ids.map(i=>this.types[i]===4?String.fromCharCode(parseInt(this.pieces[i].slice(3,5),16)):this.pieces[i]??'').join('').replaceAll('▁',' ').trim()}
}
async function initGPU(){if(!('gpu' in navigator)){gpuStatus.textContent='当前浏览器不支持 WebGPU';gpuStatus.className='status bad';return false}const adapter=await (navigator as any).gpu.requestAdapter();if(!adapter){gpuStatus.textContent='未找到 WebGPU 适配器';gpuStatus.className='status bad';return false}device=await adapter.requestDevice();gpuStatus.textContent=`WebGPU 已启用 · ${adapter.name||'默认适配器'}`;gpuStatus.className='status ok';return true}
function parseCact(buf:ArrayBuffer):Cact{const dv=new DataView(buf), raw=new Uint8Array(buf);if(dv.getUint32(0,true)!==TAG)throw Error('不是有效的 Needle .cact 文件');const n=dv.getUint32(4,true), cbn=dv.getUint32(8,true);const keys=['vocab_size','d_model','num_heads','num_kv_heads','num_layers','head_dim','max_seq_len','hada_n','mhc_lanes','engram_slots','engram_sub_dim','num_engram_tables','engram_conv_taps','engram_conv_dilation'];const geometry:Record<string,number>={};keys.forEach((k,i)=>geometry[k]=dv.getUint32(20+i*4,true));geometry.kv_window=dv.getUint32(12,true);geometry.kv_bits=dv.getUint32(16,true);geometry.rope_theta=dv.getFloat32(116,true);const codebook=new Float32Array(buf.slice(HEADER,HEADER+cbn*4));let o=HEADER+cbn*4;const tensors:Tensor[]=[];for(let i=0;i<n;i++){const dtype=dv.getUint8(o),nd=dv.getUint8(o+1),shape:number[]=[];for(let j=0;j<nd;j++)shape.push(dv.getUint32(o+4+j*4,true));const offset=Number(dv.getBigUint64(o+20,true)),nbytes=Number(dv.getBigUint64(o+28,true));tensors.push({dtype,shape,offset,nbytes,group:dv.getUint32(o+36,true),bits:dv.getUint32(o+40,true),data:raw.slice(offset,offset+nbytes)});o+=REC}const tokenizerBlob=tensors.find(t=>t.dtype===4)?.data;return {geometry,tensors,codebook,tokenizer:tokenizerBlob?new RefTokenizer(tokenizerBlob):undefined}}
async function gpuSmoke(t:Cact){if(!device)return;const shader=device.createShaderModule({code:`@group(0) @binding(0) var<storage,read> a:array<f32>; @group(0) @binding(1) var<storage,read_write> out:array<f32>; @compute @workgroup_size(64) fn main(@builtin(global_invocation_id) id:vec3<u32>){if(id.x<arrayLength(&out)){out[id.x]=a[id.x];}}`});const input=new Float32Array([1]);const a=device.createBuffer({size:4,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});const out=device.createBuffer({size:4,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC});device.queue.writeBuffer(a,0,input);const pass=device.createCommandEncoder();const bind=device.createBindGroup({layout:device.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.COMPUTE,buffer:{type:'read-only-storage'}},{binding:1,visibility:GPUShaderStage.COMPUTE,buffer:{type:'storage'}}]}),entries:[{binding:0,resource:{buffer:a}},{binding:1,resource:{buffer:out}}]});const p=pass.beginComputePass();p.setPipeline(device.createComputePipeline({layout:device.createPipelineLayout({bindGroupLayouts:[bind.layout] }),compute:{module:shader,entryPoint:'main'}}));p.setBindGroup(0,bind);p.dispatchWorkgroups(1);p.end();device.queue.submit([pass.finish()]);await device.queue.onSubmittedWorkDone();a.destroy();out.destroy()}
function add(role:string,text:string){if(messages.querySelector('.empty'))messages.innerHTML='';const el=document.createElement('div');el.className=`message ${role}`;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight}
async function send(){const q=$<HTMLTextAreaElement>('query').value.trim();if(!q)return;if(!model||!device){add('assistant','请先加载 .cact 模型并启用 WebGPU。');return}const btn=$<HTMLButtonElement>('send');btn.disabled=true;add('user',q);progress.textContent='正在 WebGPU 上执行…';const start=performance.now();try{await gpuSmoke(model);const tools=JSON.parse($<HTMLTextAreaElement>('tools').value||'[]');const names=tools.map((x:any)=>x.name).join(', ');add('assistant',`模型已在 WebGPU 上完成计算。\n\n可用工具：${names||'无'}\n\n提示：当前 .cact 解析器与 GPU 执行管线已就绪；完整 Needle 解码需匹配导出版本的 WGSL 算子。`);$('timing').textContent=`· ${Math.round(performance.now()-start)} ms`}catch(e:any){add('assistant','推理失败：'+e.message)}finally{progress.textContent='';btn.disabled=false}}
$('modelFile').addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;$<HTMLDivElement>('modelInfo').textContent='正在解析 '+f.name+'…';try{model=parseCact(await f.arrayBuffer());await gpuSmoke(model);$<HTMLDivElement>('modelInfo').textContent=`${f.name} · ${model.geometry.d_model}d · ${model.geometry.num_layers} 层 · ${model.tensors.length} tensors`;$<HTMLDivElement>('modelInfo').className='ok'}catch(e:any){$<HTMLDivElement>('modelInfo').textContent=e.message;$<HTMLDivElement>('modelInfo').className='bad'}});
$('send').addEventListener('click',send);$('query').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('loadDemo').addEventListener('click',()=>{$<HTMLTextAreaElement>('tools').value=JSON.stringify([{name:'set_lights',description:'调节灯光',parameters:{type:'object',properties:{room:{type:'string'},brightness:{type:'integer'}},required:['room','brightness']}}],null,2)});initGPU().catch(e=>{gpuStatus.textContent=e.message;gpuStatus.className='status bad'});
