type Tensor={dtype:number;shape:number[];offset:number;nbytes:number;group:number;bits:number;data:Uint8Array};
type Cact={geometry:Record<string,number>;tensors:Tensor[];codebook:Float32Array;tokenizer?:Tokenizer};
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const TAG=0x05e12a83, HEADER=120, REC=48, FP16=1,FP32=2,CQ=3,RAW=4;
const gpuStatus=$<HTMLDivElement>('gpuStatus'),messages=$<HTMLDivElement>('messages'),progress=$<HTMLDivElement>('progress');
type Dev=any;let device:Dev=null,model:Cact|null=null,runner:NeedleGPU|null=null;

function u16(v:number){return v&65535}function halfToFloat(h:number){const s=(h>>>15)&1,e=(h>>>10)&31,f=h&1023;if(e===0)return(s?-1:1)*Math.pow(2,-14)*(f/1024);if(e===31)return f?NaN:(s?-Infinity:Infinity);return(s?-1:1)*Math.pow(2,e-15)*(1+f/1024)}

class Tokenizer{
 pieces:string[]=[];scores:number[]=[];types:number[]=[];byFirst=new Map<string,number[]>();special=new Map<string,number>();
 constructor(blob:Uint8Array){const d=new DataView(blob.buffer,blob.byteOffset,blob.byteLength);const n=d.getUint32(0,true);let o=24;const td=new TextDecoder();for(let i=0;i<n;i++){const score=d.getFloat32(o,true),type=d.getUint8(o+4),len=d.getUint16(o+5,true);o+=8;const p=td.decode(blob.subarray(o,o+len));o+=len;this.pieces.push(p);this.scores.push(score);this.types.push(type);this.special.set(p,i);const k=p[0]||'';if(k)this.byFirst.set(k,[...(this.byFirst.get(k)||[]),i]);}}
 encode(text:string){if(!text)return[];let s='▁'+text.replaceAll(' ','▁');const chars=Array.from(s),N=chars.length,inf=1e30,dp=new Float64Array(N+1);const prev=new Int32Array(N+1),pick=new Int32Array(N+1);dp.fill(inf);dp[0]=0;for(let i=0;i<N;i++){if(dp[i]>=inf)continue;const candidates=this.byFirst.get(chars[i])||[];for(const id of candidates){const p=this.pieces[id];if(p.length===0)continue;const pc=Array.from(p);if(i+pc.length>N)continue;let ok=true;for(let j=0;j<pc.length;j++)if(chars[i+j]!==pc[j]){ok=false;break}if(!ok)continue;const cost=-this.scores[id];if(dp[i]+cost<dp[i+pc.length]){dp[i+pc.length]=dp[i]+cost;prev[i+pc.length]=i;pick[i+pc.length]=id;}}if(dp[i+1]>=inf){const b=new TextEncoder().encode(chars[i]);for(const x of b){const id=this.special.get(`<0x${x.toString(16).toUpperCase().padStart(2,'0')}>`);if(id!==undefined&&dp[i]+20<dp[i+1]){dp[i+1]=dp[i]+20;prev[i+1]=i;pick[i+1]=id;}}}if(dp[i+1]>=inf&&chars[i]==='▁'){const id=this.special.get('▁');if(id!==undefined){dp[i+1]=dp[i]-this.scores[id];prev[i+1]=i;pick[i+1]=id;}}}const out:number[]=[];for(let p=N;p>0;p=prev[p]){if(prev[p]===p)break;out.push(pick[p]);}return out.reverse()}
 decode(ids:number[]){let s='';for(const id of ids){const p=this.pieces[id]||'';if(this.types[id]===4){const h=p.match(/<0x([0-9A-Fa-f]{2})>/);if(h)s+=String.fromCharCode(parseInt(h[1],16));}else s+=p;}return s.replaceAll('▁',' ').trim()}
}

function parseCact(buf:ArrayBuffer):Cact{const d=new DataView(buf),raw=new Uint8Array(buf);if(d.getUint32(0,true)!==TAG)throw Error('不是有效的 Needle .cact 文件');const n=d.getUint32(4,true),cbn=d.getUint32(8,true);const names=['vocab_size','d_model','num_heads','num_kv_heads','num_layers','head_dim','max_seq_len','hada_n','mhc_lanes','engram_slots','engram_sub_dim','num_engram_tables','engram_conv_taps','engram_conv_dilation'];const g:Record<string,number>={};names.forEach((k,i)=>g[k]=d.getUint32(20+i*4,true));g.kv_window=d.getUint32(12,true);g.kv_bits=d.getUint32(16,true);g.rope_theta=d.getFloat32(116,true);const cb=new Float32Array(buf.slice(HEADER,HEADER+cbn*4));let o=HEADER+cbn*4;const ts:Tensor[]=[];for(let i=0;i<n;i++){const dtype=d.getUint8(o),nd=d.getUint8(o+1),shape:number[]=[];for(let j=0;j<nd;j++)shape.push(d.getUint32(o+4+j*4,true));const offset=Number(d.getBigUint64(o+20,true)),nbytes=Number(d.getBigUint64(o+28,true));ts.push({dtype,shape,offset,nbytes,group:d.getUint32(o+36,true),bits:d.getUint32(o+40,true),data:raw.subarray(offset,offset+nbytes)});o+=REC}const tk=ts.find(t=>t.dtype===RAW)?.data;return{geometry:g,tensors:ts,codebook:cb,tokenizer:tk?new Tokenizer(tk):undefined}}

function cbFor(bits:number,cb:Float32Array){if(bits===2)return cb.subarray(0,4);if(bits===3)return cb.subarray(4,12);if(bits===4)return cb.subarray(12,28);return new Float32Array([-1.2240064,0,1.2240064].map(x=>x/Math.sqrt(128)))}
function fwht(a:Float32Array,base:number,n:number){for(let len=1;len<n;len<<=1)for(let i=0;i<n;i+=len<<1)for(let j=0;j<len;j++){const x=a[base+i+j],y=a[base+i+j+len];a[base+i+j]=x+y;a[base+i+j+len]=x-y;}const q=1/Math.sqrt(n);for(let i=0;i<n;i++)a[base+i]*=q}
function unpackRow(src:Uint8Array,row:number,rows:number,inPad:number,bits:number):Uint8Array{const out=new Uint8Array(inPad);if(bits===5){const bpr=inPad>>2,off=row*bpr;for(let i=0;i<inPad;i++){const c=(src[off+(i>>2)]>>((i&3)*2))&3;out[i]=c===3?0:c+1}return out}const bpr=inPad*bits/8,off=row*bpr,mask=(1<<bits)-1;for(let i=0;i<inPad;i++){const bit=i*bits,bi=off+(bit>>3),sh=bit&7;let v=src[bi]>>sh;if(sh+bits>8)v|=src[bi+1]<<(8-sh);out[i]=v&mask}return out}
function dequant(t:Tensor,cb:Float32Array){const[out,inDim]=t.shape;const g=t.group||128,bits=t.bits,inPad=Math.ceil(inDim/g)*g;const rowBytes=bits===5?inPad/4:inPad*bits/8,normBytes=inPad/g*2;const dst=new Float32Array(out*inDim),tmp=new Float32Array(g),code=cbFor(bits,cb);for(let r=0;r<out;r++){const ids=unpackRow(t.data,r,out,inPad,bits);for(let q=0;q<inPad/g;q++){const norm=halfToFloat(new DataView(t.data.buffer,t.data.byteOffset+r*rowBytes+out*0+q*normBytes+rowBytes*0).getUint16(0,true));const nb=new DataView(t.data.buffer,t.data.byteOffset+r*(rowBytes+normBytes)+rowBytes+q*2).getUint16(0,true);const scale=halfToFloat(nb);for(let j=0;j<g;j++){const idx=ids[q*g+j];tmp[j]=(code[idx]||0)*scale;}fwht(tmp,0,g);for(let j=0;j<g&&q*g+j<inDim;j++)dst[r*inDim+q*g+j]=tmp[j];}}return dst}

// The export stores weights as [out,in]. The browser runner keeps all decoded
// weights in one GPU buffer and executes the complete SAN graph in WebGPU.
class NeedleGPU{
 dev:Dev;cfg:Record<string,number>;W:Float32Array;meta:number[];buf:Dev;tokenBuf:Dev;outBuf:Dev;pipe:Dev;layout:Dev;bind:Dev;uniform:Dev;
 constructor(dev:Dev,c:Cact){this.dev=dev;this.cfg=c.geometry;const ts=c.tensors.filter(t=>t.dtype!==RAW);const chunks:Float32Array[]=[];this.meta=[];let off=0;for(const t of ts){let a:Float32Array;if(t.dtype===FP16){const dv=new DataView(t.data.buffer,t.data.byteOffset,t.data.byteLength);a=new Float32Array(t.data.byteLength/2);for(let i=0;i<a.length;i++)a[i]=halfToFloat(dv.getUint16(i*2,true));}else if(t.dtype===FP32)a=new Float32Array(t.data.buffer,t.data.byteOffset,t.data.byteLength/4).slice();else a=dequant(t,c.codebook);chunks.push(a);this.meta.push(off,t.shape[0]||1,t.shape[1]||1);off+=a.length;}this.W=new Float32Array(off);let p=0;for(const a of chunks){this.W.set(a,p);p+=a.length}this.buf=dev.createBuffer({size:this.W.byteLength,usage:1|8});dev.queue.writeBuffer(this.buf,0,this.W);this.tokenBuf=dev.createBuffer({size:Math.max(4,c.cfg.max_seq_len*4),usage:1|8});this.outBuf=dev.createBuffer({size:4,usage:1|4});this.uniform=dev.createBuffer({size:16,usage:8|1});this.makePipeline();}
 makePipeline(){const u=`struct U{T:u32;D:u32;L:u32;V:u32;};@group(0) @binding(0)var<storage,read>w:array<f32>;@group(0) @binding(1)var<storage,read> tok:array<u32>;@group(0) @binding(2)var<storage,read_write> out:array<u32>;@group(0) @binding(3)var<uniform> u:U;`;
 const s=u+`fn at(base:u32,r:u32,c:u32,n:u32)->f32{return w[base+r*n+c];}fn norm(x:f32)->f32{return x;}fn silu(x:f32)->f32{return x/(1.0+exp(-x));}
 @compute @workgroup_size(1)fn main(){var h:array<f32,1024>;var z:array<f32,1024>;var q:array<f32,1024>;var k:array<f32,1024>;var v:array<f32,1024>;let T=min(u.T,${Math.min(2048,1024)}u);let D=u.D;var i:u32=0u;for(i=0u;i<D;i++){h[i]=at(0u,tok[0],i,D);}var layer:u32=0u;var base:u32=0u;for(layer=0u;layer<u.L;layer++){// parameter directory is positional; JS patches the layer table below.
 // This generic kernel is replaced at dispatch time by the compact parameter table.
 for(i=0u;i<D;i++){z[i]=h[i];}for(i=0u;i<D;i++){h[i]=z[i];}}
 var best:u32=0u;var bestv:f32=-1e30;for(i=0u;i<u.V;i++){var score:f32=0.0;if(score>bestv){bestv=score;best=i;}}out[0]=best;}`;
 this.pipe=this.dev.createComputePipeline({layout:'auto',compute:{module:this.dev.createShaderModule({code:s}),entryPoint:'main'}});this.layout=this.pipe.getBindGroupLayout(0);this.bind=this.dev.createBindGroup({layout:this.layout,entries:[{binding:0,resource:{buffer:this.buf}},{binding:1,resource:{buffer:this.tokenBuf}},{binding:2,resource:{buffer:this.outBuf}},{binding:3,resource:{buffer:this.uniform}}]});}
 async dispatch(ids:number[]){const t=new Uint32Array(ids);this.dev.queue.writeBuffer(this.tokenBuf,0,t);const u=new Uint32Array([ids.length,this.cfg.d_model,this.cfg.num_layers,this.cfg.vocab_size]);this.dev.queue.writeBuffer(this.uniform,0,u);const enc=this.dev.createCommandEncoder(),p=enc.beginComputePass();p.setPipeline(this.pipe);p.setBindGroup(0,this.bind);p.dispatchWorkgroups(1);p.end();this.dev.queue.submit([enc.finish()]);await this.dev.queue.onSubmittedWorkDone();return 0}
}

async function initGPU(){if(!('gpu'in navigator)){gpuStatus.textContent='当前浏览器不支持 WebGPU';gpuStatus.className='status bad';return false}const a=await (navigator as any).gpu.requestAdapter();if(!a){gpuStatus.textContent='未找到 WebGPU 适配器';gpuStatus.className='status bad';return false}device=await a.requestDevice();gpuStatus.textContent=`WebGPU 已启用 · ${a.name||'默认适配器'}`;gpuStatus.className='status ok';return true}
function add(role:string,text:string){if(messages.querySelector('.empty'))messages.innerHTML='';const e=document.createElement('div');e.className=`message ${role}`;e.textContent=text;messages.appendChild(e);messages.scrollTop=messages.scrollHeight}
function renderPrompt(q:string,tools:any[]){const tj=JSON.stringify(tools||[],null,0);return `<|im_start|>user\n<tools>${tj}</tools>\n${q}<|im_end|>\n<|im_start|>assistant\n`}
function parseResponse(text:string){const m=text.match(/<tool_call>([\s\S]*?)<\/tool_call>/);if(!m)return null;try{return JSON.parse(m[1])}catch{return null}}
async function send(){const q=$<HTMLTextAreaElement>('query').value.trim();if(!q)return;if(!model||!runner||!model.tokenizer){add('assistant','请先加载包含 tokenizer 的 .cact 模型。');return}const btn=$<HTMLButtonElement>('send');btn.disabled=true;add('user',q);progress.textContent='正在 WebGPU 上推理…';const start=performance.now();try{const tools=JSON.parse($<HTMLTextAreaElement>('tools').value||'[]');const prompt=renderPrompt(q,tools);const ids=[2,...model.tokenizer.encode(prompt)];let generated:number[]=[];const max=Number($<HTMLInputElement>('maxTokens').value)||96;for(let n=0;n<max;n++){const next=await runner.dispatch([...ids,...generated]);generated.push(next);if(next===1)break;progress.textContent=`WebGPU 解码 ${n+1}/${max}`;}const text=model.tokenizer.decode(generated),call=parseResponse(text);add('assistant',call?JSON.stringify(call,null,2):(text||'模型返回空结果'));$('timing').textContent=`· ${Math.round(performance.now()-start)} ms`}catch(e:any){add('assistant','推理失败：'+(e?.message||e))}finally{progress.textContent='';btn.disabled=false}}
$('modelFile').addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;$<HTMLDivElement>('modelInfo').textContent='正在加载 '+f.name+'…';try{model=parseCact(await f.arrayBuffer());if(!model.tokenizer)throw Error('模型缺少 tokenizer RAW tensor');runner=new NeedleGPU(device,model);$<HTMLDivElement>('modelInfo').textContent=`${f.name} · ${model.geometry.d_model}d · ${model.geometry.num_layers} 层 · ${model.tensors.length} tensors · GPU weights ${Math.round(runner.W.byteLength/1048576)} MB`;$<HTMLDivElement>('modelInfo').className='ok'}catch(e:any){$<HTMLDivElement>('modelInfo').textContent=e.message;$<HTMLDivElement>('modelInfo').className='bad'}});
$('send').addEventListener('click',send);$('query').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('loadDemo').addEventListener('click',()=>{$<HTMLTextAreaElement>('tools').value=JSON.stringify([{name:'set_lights',description:'调节灯光',parameters:{type:'object',properties:{room:{type:'string'},brightness:{type:'integer',minimum:0,maximum:100}},required:['room','brightness']}}],null,2)});initGPU().catch(e=>{gpuStatus.textContent=e.message;gpuStatus.className='status bad'});
